<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Sebastians-MBP" failures="1" tests="4" name="com.console.RunScript" time="35.540" errors="0" timestamp="12 Mar 2021 20:26:36 GMT" skipped="0">
  <testcase classname="com.console.RunScript" name="runScript" time="3.248"/>
  <testcase classname="com.console.RunScript" name="runScript" time="17.056">
    <failure message="Cucumber feature file failed." type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Cucumber feature file failed.
	at org.junit.Assert.fail(Assert.java:89)
	at com.ucf.pcte.CucumberKW.runFeatureFile(CucumberKW.java:48)
	at com.ucf.pcte.CucumberKW$runFeatureFile.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
	at Script1611241895950.run(Script1611241895950.groovy:11)
	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:427)
	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:470)
	at com.console.RunScript.runScript(RunScript.java:50)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at com.console.Execute.run(Execute.java:89)
	at com.console.RunConsole.console(RunConsole.java:67)
	at com.console.Main.main(Main.java:98)
]]>
    </failure>
  </testcase> <!-- runScript -->
  <testcase classname="com.console.RunScript" name="runScript" time="8.176"/>
  <testcase classname="com.console.RunScript" name="runScript" time="7.060"/>
</testsuite> <!-- com.console.RunScript -->
